INSERT INTO public.products (product_id, image, name, price, attribute_id, category_id, status) VALUES (57, 'image/Rubber Logo Keychain', 'Rubber Logo Keychain', '8', 55, 8, true);
INSERT INTO public.products (product_id, image, name, price, attribute_id, category_id, status) VALUES (161, 'image/Desert Tee', 'Desert Tee', '122', 157, 7, true);
INSERT INTO public.products (product_id, image, name, price, attribute_id, category_id, status) VALUES (66, '/image/Floret Dad Hat', 'Floret Dad Hat', '30', 64, 11, true);
INSERT INTO public.products (product_id, image, name, price, attribute_id, category_id, status) VALUES (69, 'image/BL Earrings', 'BL Earrings', '10', 67, 12, true);
INSERT INTO public.products (product_id, image, name, price, attribute_id, category_id, status) VALUES (2, '/image/Belt in Jeans', 'Belt in Jeans', '65', 2, 5, true);
INSERT INTO public.products (product_id, image, name, price, attribute_id, category_id, status) VALUES (21, '/resources/images/item.jpg', 'CB 400', '761', 18, 10, true);
INSERT INTO public.products (product_id, image, name, price, attribute_id, category_id, status) VALUES (245, '/image/245', 'Curb Rats Jacket', '76', 242, 3, true);
INSERT INTO public.products (product_id, image, name, price, attribute_id, category_id, status) VALUES (127, '/image/127', 'Lakeview Tank', '32', 125, 5, true);
INSERT INTO public.products (product_id, image, name, price, attribute_id, category_id, status) VALUES (63, '/image/Transient Jacket', 'Transient Jacket', '98', 58, 3, true);
INSERT INTO public.products (product_id, image, name, price, attribute_id, category_id, status) VALUES (1, '/image/1', 'Owl from Adidas', '45', 1, 6, false);
INSERT INTO public.products (product_id, image, name, price, attribute_id, category_id, status) VALUES (147, '/image/147', 'Brainfuck Tee', '157', 143, 7, true);
INSERT INTO public.products (product_id, image, name, price, attribute_id, category_id, status) VALUES (15, '/image/15', 'Arctic Burn', '213', 13, 4, true);
INSERT INTO public.products (product_id, image, name, price, attribute_id, category_id, status) VALUES (3, '/image/3', 'Leggins', '400', 3, 10, true);
INSERT INTO public.products (product_id, image, name, price, attribute_id, category_id, status) VALUES (132, '/image/132', 'Sanctified Tee', '32', 129, 5, true);